all:
  children:
    manager:
      hosts:
        Petclinic-Manager:
    worker:
      hosts:
        Petclinic-Worker:
    nginx-lb:
      hosts:
        Petclinic-Nginx:

  vars:
    ansible_user: ubuntu
    ansible_ssh_private_key_file: '~/.ssh/aws-key-london.pem'
    ansible_ssh_common_args: '-o StrictHostKeyChecking=no'